// Code generated by Kitex v0.12.3. DO NOT EDIT.

package videoservice

import (
	"context"
	"errors"

	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	video "github.com/yxrxy/videoHub/kitex_gen/video"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Publish": kitex.NewMethodInfo(
		publishHandler,
		newVideoServicePublishArgs,
		newVideoServicePublishResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"List": kitex.NewMethodInfo(
		listHandler,
		newVideoServiceListArgs,
		newVideoServiceListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Detail": kitex.NewMethodInfo(
		detailHandler,
		newVideoServiceDetailArgs,
		newVideoServiceDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetHotVideos": kitex.NewMethodInfo(
		getHotVideosHandler,
		newVideoServiceGetHotVideosArgs,
		newVideoServiceGetHotVideosResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Delete": kitex.NewMethodInfo(
		deleteHandler,
		newVideoServiceDeleteArgs,
		newVideoServiceDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"IncrementVisitCount": kitex.NewMethodInfo(
		incrementVisitCountHandler,
		newVideoServiceIncrementVisitCountArgs,
		newVideoServiceIncrementVisitCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"IncrementLikeCount": kitex.NewMethodInfo(
		incrementLikeCountHandler,
		newVideoServiceIncrementLikeCountArgs,
		newVideoServiceIncrementLikeCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Search": kitex.NewMethodInfo(
		searchHandler,
		newVideoServiceSearchArgs,
		newVideoServiceSearchResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	videoServiceServiceInfo                = NewServiceInfo()
	videoServiceServiceInfoForClient       = NewServiceInfoForClient()
	videoServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return videoServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return videoServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return videoServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "VideoService"
	handlerType := (*video.VideoService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "video",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func publishHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServicePublishArgs)
	realResult := result.(*video.VideoServicePublishResult)
	success, err := handler.(video.VideoService).Publish(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServicePublishArgs() interface{} {
	return video.NewVideoServicePublishArgs()
}

func newVideoServicePublishResult() interface{} {
	return video.NewVideoServicePublishResult()
}

func listHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceListArgs)
	realResult := result.(*video.VideoServiceListResult)
	success, err := handler.(video.VideoService).List(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceListArgs() interface{} {
	return video.NewVideoServiceListArgs()
}

func newVideoServiceListResult() interface{} {
	return video.NewVideoServiceListResult()
}

func detailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceDetailArgs)
	realResult := result.(*video.VideoServiceDetailResult)
	success, err := handler.(video.VideoService).Detail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceDetailArgs() interface{} {
	return video.NewVideoServiceDetailArgs()
}

func newVideoServiceDetailResult() interface{} {
	return video.NewVideoServiceDetailResult()
}

func getHotVideosHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceGetHotVideosArgs)
	realResult := result.(*video.VideoServiceGetHotVideosResult)
	success, err := handler.(video.VideoService).GetHotVideos(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceGetHotVideosArgs() interface{} {
	return video.NewVideoServiceGetHotVideosArgs()
}

func newVideoServiceGetHotVideosResult() interface{} {
	return video.NewVideoServiceGetHotVideosResult()
}

func deleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceDeleteArgs)
	realResult := result.(*video.VideoServiceDeleteResult)
	success, err := handler.(video.VideoService).Delete(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceDeleteArgs() interface{} {
	return video.NewVideoServiceDeleteArgs()
}

func newVideoServiceDeleteResult() interface{} {
	return video.NewVideoServiceDeleteResult()
}

func incrementVisitCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceIncrementVisitCountArgs)
	realResult := result.(*video.VideoServiceIncrementVisitCountResult)
	success, err := handler.(video.VideoService).IncrementVisitCount(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceIncrementVisitCountArgs() interface{} {
	return video.NewVideoServiceIncrementVisitCountArgs()
}

func newVideoServiceIncrementVisitCountResult() interface{} {
	return video.NewVideoServiceIncrementVisitCountResult()
}

func incrementLikeCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceIncrementLikeCountArgs)
	realResult := result.(*video.VideoServiceIncrementLikeCountResult)
	success, err := handler.(video.VideoService).IncrementLikeCount(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceIncrementLikeCountArgs() interface{} {
	return video.NewVideoServiceIncrementLikeCountArgs()
}

func newVideoServiceIncrementLikeCountResult() interface{} {
	return video.NewVideoServiceIncrementLikeCountResult()
}

func searchHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceSearchArgs)
	realResult := result.(*video.VideoServiceSearchResult)
	success, err := handler.(video.VideoService).Search(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceSearchArgs() interface{} {
	return video.NewVideoServiceSearchArgs()
}

func newVideoServiceSearchResult() interface{} {
	return video.NewVideoServiceSearchResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Publish(ctx context.Context, req *video.PublishRequest) (r *video.PublishResponse, err error) {
	var _args video.VideoServicePublishArgs
	_args.Req = req
	var _result video.VideoServicePublishResult
	if err = p.c.Call(ctx, "Publish", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) List(ctx context.Context, req *video.VideoListRequest) (r *video.VideoListResponse, err error) {
	var _args video.VideoServiceListArgs
	_args.Req = req
	var _result video.VideoServiceListResult
	if err = p.c.Call(ctx, "List", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Detail(ctx context.Context, req *video.DetailRequest) (r *video.DetailResponse, err error) {
	var _args video.VideoServiceDetailArgs
	_args.Req = req
	var _result video.VideoServiceDetailResult
	if err = p.c.Call(ctx, "Detail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetHotVideos(ctx context.Context, req *video.HotVideoRequest) (r *video.HotVideoResponse, err error) {
	var _args video.VideoServiceGetHotVideosArgs
	_args.Req = req
	var _result video.VideoServiceGetHotVideosResult
	if err = p.c.Call(ctx, "GetHotVideos", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Delete(ctx context.Context, req *video.DeleteRequest) (r *video.DeleteResponse, err error) {
	var _args video.VideoServiceDeleteArgs
	_args.Req = req
	var _result video.VideoServiceDeleteResult
	if err = p.c.Call(ctx, "Delete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IncrementVisitCount(ctx context.Context, req *video.IncrementVisitCountRequest) (r *video.IncrementVisitCountResponse, err error) {
	var _args video.VideoServiceIncrementVisitCountArgs
	_args.Req = req
	var _result video.VideoServiceIncrementVisitCountResult
	if err = p.c.Call(ctx, "IncrementVisitCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IncrementLikeCount(ctx context.Context, req *video.IncrementLikeCountRequest) (r *video.IncrementLikeCountResponse, err error) {
	var _args video.VideoServiceIncrementLikeCountArgs
	_args.Req = req
	var _result video.VideoServiceIncrementLikeCountResult
	if err = p.c.Call(ctx, "IncrementLikeCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Search(ctx context.Context, req *video.SearchRequest) (r *video.SearchResponse, err error) {
	var _args video.VideoServiceSearchArgs
	_args.Req = req
	var _result video.VideoServiceSearchResult
	if err = p.c.Call(ctx, "Search", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
