version: "2"
run:
  concurrency: 16
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - asciicheck
    - copyloopvar
    - decorder
    - errcheck
    - errorlint
    - forcetypeassert
    - gocritic
    - govet
    - importas
    - inamedparam
    - ineffassign
    - lll
    - makezero
    - mirror
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - staticcheck
    - tagalign
    - unconvert
    - unused
    - whitespace

linters-settings:
  errorlint:
    errorf: true
    errorf-multi: true
    asserts: true
    comparison: true
  lll:
    line-length: 160
    tab-width: 1
  makezero:
    always: false
  misspell:
    locale: US
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - "0666"
      - "0755"
      - "42"
    ignored-functions:
      - ^math\.
      - ^http\.StatusText$
  nakedret:
    max-func-lines: 31
  nestif:
    min-complexity: 6
  staticcheck:
    checks:
      - all
      - -SA1019
  tagalign:
    align: true
    sort: true
    order:
      - json
      - yaml
      - yml
      - toml
      - mapstructure
      - binding
      - validate
    strict: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: third_party/
      linters:
        - all
    - path: examples/
      linters:
        - all
