version: '3'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app_net

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping", "-h", "localhost", "-p", "6379", "-a", "${REDIS_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app_net

  etcd:
    build:
      context: ./etcd
      dockerfile: Dockerfile
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/bitnami/etcd
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  etcd_data:  
