cluster.name: "docker-cluster"
network.host: 0.0.0.0

cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 98%
cluster.routing.allocation.disk.watermark.high: 99%
cluster.routing.allocation.disk.watermark.flood_stage: 99.5%
cluster.info.update.interval: 1m
