// Code generated by Kitex v0.13.1. DO NOT EDIT.

package interactionservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	interaction "github.com/yxrxy/videoHub/kitex_gen/interaction"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Like(ctx context.Context, req *interaction.LikeRequest, callOptions ...callopt.Option) (r *interaction.LikeResponse, err error)
	GetLikes(ctx context.Context, req *interaction.GetLikesRequest, callOptions ...callopt.Option) (r *interaction.GetLikesResponse, err error)
	Comment(ctx context.Context, req *interaction.CommentRequest, callOptions ...callopt.Option) (r *interaction.CommentResponse, err error)
	GetComments(ctx context.Context, req *interaction.GetCommentsRequest, callOptions ...callopt.Option) (r *interaction.GetCommentsResponse, err error)
	DeleteComment(ctx context.Context, req *interaction.DeleteCommentRequest, callOptions ...callopt.Option) (r *interaction.DeleteCommentResponse, err error)
	LikeComment(ctx context.Context, req *interaction.LikeCommentRequest, callOptions ...callopt.Option) (r *interaction.LikeCommentResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kInteractionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInteractionServiceClient struct {
	*kClient
}

func (p *kInteractionServiceClient) Like(ctx context.Context, req *interaction.LikeRequest, callOptions ...callopt.Option) (r *interaction.LikeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Like(ctx, req)
}

func (p *kInteractionServiceClient) GetLikes(ctx context.Context, req *interaction.GetLikesRequest, callOptions ...callopt.Option) (r *interaction.GetLikesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLikes(ctx, req)
}

func (p *kInteractionServiceClient) Comment(ctx context.Context, req *interaction.CommentRequest, callOptions ...callopt.Option) (r *interaction.CommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Comment(ctx, req)
}

func (p *kInteractionServiceClient) GetComments(ctx context.Context, req *interaction.GetCommentsRequest, callOptions ...callopt.Option) (r *interaction.GetCommentsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetComments(ctx, req)
}

func (p *kInteractionServiceClient) DeleteComment(ctx context.Context, req *interaction.DeleteCommentRequest, callOptions ...callopt.Option) (r *interaction.DeleteCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteComment(ctx, req)
}

func (p *kInteractionServiceClient) LikeComment(ctx context.Context, req *interaction.LikeCommentRequest, callOptions ...callopt.Option) (r *interaction.LikeCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LikeComment(ctx, req)
}
