// Code generated by Kitex v0.12.3. DO NOT EDIT.

package interactionservice

import (
	"context"
	"errors"

	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	interaction "github.com/yxrxy/videoHub/kitex_gen/interaction"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Like": kitex.NewMethodInfo(
		likeHandler,
		newInteractionServiceLikeArgs,
		newInteractionServiceLikeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLikes": kitex.NewMethodInfo(
		getLikesHandler,
		newInteractionServiceGetLikesArgs,
		newInteractionServiceGetLikesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Comment": kitex.NewMethodInfo(
		commentHandler,
		newInteractionServiceCommentArgs,
		newInteractionServiceCommentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetComments": kitex.NewMethodInfo(
		getCommentsHandler,
		newInteractionServiceGetCommentsArgs,
		newInteractionServiceGetCommentsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteComment": kitex.NewMethodInfo(
		deleteCommentHandler,
		newInteractionServiceDeleteCommentArgs,
		newInteractionServiceDeleteCommentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LikeComment": kitex.NewMethodInfo(
		likeCommentHandler,
		newInteractionServiceLikeCommentArgs,
		newInteractionServiceLikeCommentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	interactionServiceServiceInfo                = NewServiceInfo()
	interactionServiceServiceInfoForClient       = NewServiceInfoForClient()
	interactionServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return interactionServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return interactionServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return interactionServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "InteractionService"
	handlerType := (*interaction.InteractionService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "interaction",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func likeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceLikeArgs)
	realResult := result.(*interaction.InteractionServiceLikeResult)
	success, err := handler.(interaction.InteractionService).Like(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceLikeArgs() interface{} {
	return interaction.NewInteractionServiceLikeArgs()
}

func newInteractionServiceLikeResult() interface{} {
	return interaction.NewInteractionServiceLikeResult()
}

func getLikesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceGetLikesArgs)
	realResult := result.(*interaction.InteractionServiceGetLikesResult)
	success, err := handler.(interaction.InteractionService).GetLikes(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceGetLikesArgs() interface{} {
	return interaction.NewInteractionServiceGetLikesArgs()
}

func newInteractionServiceGetLikesResult() interface{} {
	return interaction.NewInteractionServiceGetLikesResult()
}

func commentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceCommentArgs)
	realResult := result.(*interaction.InteractionServiceCommentResult)
	success, err := handler.(interaction.InteractionService).Comment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceCommentArgs() interface{} {
	return interaction.NewInteractionServiceCommentArgs()
}

func newInteractionServiceCommentResult() interface{} {
	return interaction.NewInteractionServiceCommentResult()
}

func getCommentsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceGetCommentsArgs)
	realResult := result.(*interaction.InteractionServiceGetCommentsResult)
	success, err := handler.(interaction.InteractionService).GetComments(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceGetCommentsArgs() interface{} {
	return interaction.NewInteractionServiceGetCommentsArgs()
}

func newInteractionServiceGetCommentsResult() interface{} {
	return interaction.NewInteractionServiceGetCommentsResult()
}

func deleteCommentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceDeleteCommentArgs)
	realResult := result.(*interaction.InteractionServiceDeleteCommentResult)
	success, err := handler.(interaction.InteractionService).DeleteComment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceDeleteCommentArgs() interface{} {
	return interaction.NewInteractionServiceDeleteCommentArgs()
}

func newInteractionServiceDeleteCommentResult() interface{} {
	return interaction.NewInteractionServiceDeleteCommentResult()
}

func likeCommentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceLikeCommentArgs)
	realResult := result.(*interaction.InteractionServiceLikeCommentResult)
	success, err := handler.(interaction.InteractionService).LikeComment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceLikeCommentArgs() interface{} {
	return interaction.NewInteractionServiceLikeCommentArgs()
}

func newInteractionServiceLikeCommentResult() interface{} {
	return interaction.NewInteractionServiceLikeCommentResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Like(ctx context.Context, req *interaction.LikeRequest) (r *interaction.LikeResponse, err error) {
	var _args interaction.InteractionServiceLikeArgs
	_args.Req = req
	var _result interaction.InteractionServiceLikeResult
	if err = p.c.Call(ctx, "Like", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLikes(ctx context.Context, req *interaction.GetLikesRequest) (r *interaction.GetLikesResponse, err error) {
	var _args interaction.InteractionServiceGetLikesArgs
	_args.Req = req
	var _result interaction.InteractionServiceGetLikesResult
	if err = p.c.Call(ctx, "GetLikes", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Comment(ctx context.Context, req *interaction.CommentRequest) (r *interaction.CommentResponse, err error) {
	var _args interaction.InteractionServiceCommentArgs
	_args.Req = req
	var _result interaction.InteractionServiceCommentResult
	if err = p.c.Call(ctx, "Comment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetComments(ctx context.Context, req *interaction.GetCommentsRequest) (r *interaction.GetCommentsResponse, err error) {
	var _args interaction.InteractionServiceGetCommentsArgs
	_args.Req = req
	var _result interaction.InteractionServiceGetCommentsResult
	if err = p.c.Call(ctx, "GetComments", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteComment(ctx context.Context, req *interaction.DeleteCommentRequest) (r *interaction.DeleteCommentResponse, err error) {
	var _args interaction.InteractionServiceDeleteCommentArgs
	_args.Req = req
	var _result interaction.InteractionServiceDeleteCommentResult
	if err = p.c.Call(ctx, "DeleteComment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LikeComment(ctx context.Context, req *interaction.LikeCommentRequest) (r *interaction.LikeCommentResponse, err error) {
	var _args interaction.InteractionServiceLikeCommentArgs
	_args.Req = req
	var _result interaction.InteractionServiceLikeCommentResult
	if err = p.c.Call(ctx, "LikeComment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
